/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Neo-brutalism color palette
        'neo': {
          50: '#fdf4ff',
          100: '#fae8ff',
          200: '#f5d0fe',
          300: '#f0abfc',
          400: '#e879f9',
          500: '#d946ef',
          600: '#c026d3',
          700: '#a21caf',
          800: '#86198f',
          900: '#701a75',
        },
        // Glassmorphism colors
        'glass': {
          primary: 'rgba(255, 255, 255, 0.1)',
          secondary: 'rgba(255, 255, 255, 0.05)',
          accent: 'rgba(217, 70, 239, 0.1)',
          dark: 'rgba(0, 0, 0, 0.2)',
          blur: 'rgba(255, 255, 255, 0.8)',
        },
        // Dynamic gradient colors
        'gradient': {
          productivity: {
            from: '#8b5cf6',
            to: '#06b6d4',
          },
          creativity: {
            from: '#f97316',
            to: '#ec4899',
          },
          focus: {
            from: '#10b981',
            to: '#3b82f6',
          },
          energy: {
            from: '#f59e0b',
            to: '#ef4444',
          },
        },
        // Aurora Borealis inspired
        'aurora': {
          green: '#00ff88',
          blue: '#00d4ff',
          purple: '#9d4edd',
          pink: '#ff6b9d',
          yellow: '#ffd93d',
        },
        // Synesthetic colors
        'synesthetic': {
          sound: '#ff6b6b',
          emotion: '#4ecdc4',
          movement: '#45b7d1',
          texture: '#96ceb4',
          energy: '#ffeaa7',
        }
      },
      fontFamily: {
        'display': ['Inter', 'system-ui', 'sans-serif'],
        'mono': ['JetBrains Mono', 'Fira Code', 'monospace'],
        'handwriting': ['Caveat', 'cursive'],
      },
      fontSize: {
        'xs': ['0.75rem', { lineHeight: '1rem' }],
        'sm': ['0.875rem', { lineHeight: '1.25rem' }],
        'base': ['1rem', { lineHeight: '1.5rem' }],
        'lg': ['1.125rem', { lineHeight: '1.75rem' }],
        'xl': ['1.25rem', { lineHeight: '1.75rem' }],
        '2xl': ['1.5rem', { lineHeight: '2rem' }],
        '3xl': ['1.875rem', { lineHeight: '2.25rem' }],
        '4xl': ['2.25rem', { lineHeight: '2.5rem' }],
        '5xl': ['3rem', { lineHeight: '1' }],
        '6xl': ['3.75rem', { lineHeight: '1' }],
        '7xl': ['4.5rem', { lineHeight: '1' }],
        '8xl': ['6rem', { lineHeight: '1' }],
        '9xl': ['8rem', { lineHeight: '1' }],
      },
      spacing: {
        '18': '4.5rem',
        '88': '22rem',
        '128': '32rem',
        '144': '36rem',
      },
      borderRadius: {
        '4xl': '2rem',
        '5xl': '2.5rem',
        '6xl': '3rem',
      },
      backdropBlur: {
        xs: '2px',
      },
      animation: {
        // Micro-animations
        'float': 'float 6s ease-in-out infinite',
        'pulse-slow': 'pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'bounce-slow': 'bounce 3s infinite',
        'spin-slow': 'spin 8s linear infinite',
        'wiggle': 'wiggle 1s ease-in-out infinite',
        'morph': 'morph 8s ease-in-out infinite',
        'aurora': 'aurora 60s linear infinite',
        'particle': 'particle 20s linear infinite',
        'ripple': 'ripple 1s cubic-bezier(0, 0, 0.2, 1) infinite',
        'slide-up': 'slideUp 0.5s ease-out',
        'slide-down': 'slideDown 0.5s ease-out',
        'fade-in': 'fadeIn 0.5s ease-out',
        'scale-in': 'scaleIn 0.3s ease-out',
        'rotate-in': 'rotateIn 0.5s ease-out',
        'slide-in-left': 'slideInLeft 0.5s ease-out',
        'slide-in-right': 'slideInRight 0.5s ease-out',
        'slide-in-top': 'slideInTop 0.5s ease-out',
        'slide-in-bottom': 'slideInBottom 0.5s ease-out',
        'zoom-in': 'zoomIn 0.3s ease-out',
        'zoom-out': 'zoomOut 0.3s ease-out',
        'flip-in': 'flipIn 0.6s ease-out',
        'flip-out': 'flipOut 0.6s ease-out',
        'hinge': 'hinge 2s ease-in-out',
        'jack-in-the-box': 'jackInTheBox 0.5s ease-out',
        'roll-in': 'rollIn 0.6s ease-out',
        'roll-out': 'rollOut 0.6s ease-out',
        'swing': 'swing 1s ease-in-out',
        'tada': 'tada 1s ease-in-out',
        'wobble': 'wobble 1s ease-in-out',
        'jello': 'jello 1s ease-in-out',
        'heart-beat': 'heartBeat 1.3s ease-in-out infinite',
        'rubber-band': 'rubberBand 1s ease-in-out',
        'shake': 'shake 0.82s cubic-bezier(.36,.07,.19,.97) both',
        'head-shake': 'headShake 1s ease-in-out',
        'swash-in': 'swashIn 0.5s ease-out',
        'swash-out': 'swashOut 0.5s ease-out',
        'foolish-in': 'foolishIn 0.5s ease-out',
        'foolish-out': 'foolishOut 0.5s ease-out',
        'hole-in': 'holeIn 0.5s ease-out',
        'hole-out': 'holeOut 0.5s ease-out',
        'horror-in': 'horrorIn 0.5s ease-out',
        'horror-out': 'horrorOut 0.5s ease-out',
        'space-in-up': 'spaceInUp 0.5s ease-out',
        'space-in-right': 'spaceInRight 0.5s ease-out',
        'space-in-down': 'spaceInDown 0.5s ease-out',
        'space-in-left': 'spaceInLeft 0.5s ease-out',
        'space-out-up': 'spaceOutUp 0.5s ease-out',
        'space-out-right': 'spaceOutRight 0.5s ease-out',
        'space-out-down': 'spaceOutDown 0.5s ease-out',
        'space-out-left': 'spaceOutLeft 0.5s ease-out',
        'grow-in': 'growIn 0.5s ease-out',
        'grow-out': 'growOut 0.5s ease-out',
        'shrink-in': 'shrinkIn 0.5s ease-out',
        'shrink-out': 'shrinkOut 0.5s ease-out',
        'rotate-in-down-left': 'rotateInDownLeft 0.5s ease-out',
        'rotate-in-down-right': 'rotateInDownRight 0.5s ease-out',
        'rotate-in-up-left': 'rotateInUpLeft 0.5s ease-out',
        'rotate-in-up-right': 'rotateInUpRight 0.5s ease-out',
        'rotate-out-down-left': 'rotateOutDownLeft 0.5s ease-out',
        'rotate-out-down-right': 'rotateOutDownRight 0.5s ease-out',
        'rotate-out-up-left': 'rotateOutUpLeft 0.5s ease-out',
        'rotate-out-up-right': 'rotateOutUpRight 0.5s ease-out',
        'slide-in-up': 'slideInUp 0.5s ease-out',
        'slide-in-down': 'slideInDown 0.5s ease-out',
        'slide-in-left': 'slideInLeft 0.5s ease-out',
        'slide-in-right': 'slideInRight 0.5s ease-out',
        'slide-out-up': 'slideOutUp 0.5s ease-out',
        'slide-out-down': 'slideOutDown 0.5s ease-out',
        'slide-out-left': 'slideOutLeft 0.5s ease-out',
        'slide-out-right': 'slideOutRight 0.5s ease-out',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-20px)' },
        },
        morph: {
          '0%, 100%': { borderRadius: '60% 40% 30% 70%/60% 30% 70% 40%' },
          '50%': { borderRadius: '30% 60% 70% 40%/50% 60% 30% 60%' },
        },
        aurora: {
          '0%': { backgroundPosition: '0% 50%' },
          '50%': { backgroundPosition: '100% 50%' },
          '100%': { backgroundPosition: '0% 50%' },
        },
        particle: {
          '0%': { transform: 'translateY(0px) rotate(0deg)', opacity: '1' },
          '100%': { transform: 'translateY(-1000px) rotate(720deg)', opacity: '0' },
        },
        ripple: {
          '0%': { transform: 'scale(0)', opacity: '1' },
          '100%': { transform: 'scale(4)', opacity: '0' },
        },
        slideUp: {
          '0%': { transform: 'translateY(100%)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideDown: {
          '0%': { transform: 'translateY(-100%)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        scaleIn: {
          '0%': { transform: 'scale(0)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        rotateIn: {
          '0%': { transform: 'rotate(-200deg)', opacity: '0' },
          '100%': { transform: 'rotate(0)', opacity: '1' },
        },
        slideInLeft: {
          '0%': { transform: 'translateX(-100%)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        slideInRight: {
          '0%': { transform: 'translateX(100%)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        slideInTop: {
          '0%': { transform: 'translateY(-100%)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideInBottom: {
          '0%': { transform: 'translateY(100%)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        zoomIn: {
          '0%': { transform: 'scale(0.3)', opacity: '0' },
          '50%': { opacity: '1' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        zoomOut: {
          '0%': { transform: 'scale(1)', opacity: '1' },
          '50%': { opacity: '1' },
          '100%': { transform: 'scale(0.3)', opacity: '0' },
        },
        flipIn: {
          '0%': { transform: 'perspective(400px) rotateY(90deg)', opacity: '0' },
          '40%': { transform: 'perspective(400px) rotateY(-20deg)' },
          '60%': { transform: 'perspective(400px) rotateY(10deg)' },
          '80%': { transform: 'perspective(400px) rotateY(-5deg)' },
          '100%': { transform: 'perspective(400px) rotateY(0deg)', opacity: '1' },
        },
        flipOut: {
          '0%': { transform: 'perspective(400px) rotateY(0deg)', opacity: '1' },
          '100%': { transform: 'perspective(400px) rotateY(90deg)', opacity: '0' },
        },
        wiggle: {
          '0%, 100%': { transform: 'rotate(-3deg)' },
          '50%': { transform: 'rotate(3deg)' },
        },
        heartBeat: {
          '0%': { transform: 'scale(1)' },
          '14%': { transform: 'scale(1.3)' },
          '28%': { transform: 'scale(1)' },
          '42%': { transform: 'scale(1.3)' },
          '70%': { transform: 'scale(1)' },
        },
        shake: {
          '10%, 90%': { transform: 'translate3d(-1px, 0, 0)' },
          '20%, 80%': { transform: 'translate3d(2px, 0, 0)' },
          '30%, 50%, 70%': { transform: 'translate3d(-4px, 0, 0)' },
          '40%, 60%': { transform: 'translate3d(4px, 0, 0)' },
        },
      },
      boxShadow: {
        'neo': '4px 4px 0px 0px rgba(0, 0, 0, 0.9)',
        'neo-lg': '8px 8px 0px 0px rgba(0, 0, 0, 0.9)',
        'neo-xl': '12px 12px 0px 0px rgba(0, 0, 0, 0.9)',
        'glass': '0 8px 32px 0 rgba(31, 38, 135, 0.37)',
        'glass-lg': '0 16px 64px 0 rgba(31, 38, 135, 0.37)',
        'aurora': '0 0 20px rgba(0, 255, 136, 0.5)',
        'aurora-lg': '0 0 40px rgba(0, 255, 136, 0.5)',
        'floating': '0 20px 40px rgba(0, 0, 0, 0.1)',
        'floating-lg': '0 40px 80px rgba(0, 0, 0, 0.1)',
        'inner-glow': 'inset 0 0 20px rgba(217, 70, 239, 0.3)',
        'outer-glow': '0 0 20px rgba(217, 70, 239, 0.5)',
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
        'aurora-gradient': 'linear-gradient(45deg, #00ff88, #00d4ff, #9d4edd, #ff6b9d, #ffd93d)',
        'productivity-gradient': 'linear-gradient(135deg, #8b5cf6 0%, #06b6d4 100%)',
        'creativity-gradient': 'linear-gradient(135deg, #f97316 0%, #ec4899 100%)',
        'focus-gradient': 'linear-gradient(135deg, #10b981 0%, #3b82f6 100%)',
        'energy-gradient': 'linear-gradient(135deg, #f59e0b 0%, #ef4444 100%)',
        'glass-gradient': 'linear-gradient(135deg, rgba(255, 255, 255, 0.1) 0%, rgba(255, 255, 255, 0.05) 100%)',
        'noise': "url(\"data:image/svg+xml,%3Csvg viewBox='0 0 200 200' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='noiseFilter'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.65' numOctaves='3' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23noiseFilter)'/%3E%3C/svg%3E\")",
      },
      backdropFilter: {
        'none': 'none',
        'blur': 'blur(20px)',
        'blur-sm': 'blur(4px)',
        'blur-md': 'blur(12px)',
        'blur-lg': 'blur(16px)',
        'blur-xl': 'blur(24px)',
        'blur-2xl': 'blur(40px)',
        'blur-3xl': 'blur(64px)',
      },
      transitionProperty: {
        'height': 'height',
        'spacing': 'margin, padding',
        'all': 'all',
      },
      transitionDuration: {
        '0': '0ms',
        '75': '75ms',
        '100': '100ms',
        '150': '150ms',
        '200': '200ms',
        '300': '300ms',
        '500': '500ms',
        '700': '700ms',
        '1000': '1000ms',
      },
      transitionTimingFunction: {
        'bounce': 'cubic-bezier(0.68, -0.55, 0.265, 1.55)',
        'elastic': 'cubic-bezier(0.175, 0.885, 0.32, 1.275)',
        'smooth': 'cubic-bezier(0.4, 0, 0.2, 1)',
        'sharp': 'cubic-bezier(0.4, 0, 0.6, 1)',
      },
    },
  },
  plugins: [],
} 